[MVP1] Some feature implementation of bigquery source
streamnative/pulsar-io-bigquery pull request #105
Opened 2022-09-16 10:26 UTC by danpi

### Motivation

[#5](https://github.com/streamnative/ecosystem-projects/issues/5)

### Modifications

*Describe the modifications you've done.*

### Change
- [ ] 1. Support table snapshot.
- [ ] 2. Support filter result.
- [ ] 3. Breakpoint resume.
- [ ] 4. Unit test of key part.
- [ ] 5. Finish state check.
- [ ] 6. Support Avro format to transmit.
- [ ] 7. Preliminary integration tests were run to verify functional correctness.
- [ ] 8. Performance testing and stress testing.

### Documentation

Check the box below.

Need to update docs? 

- [ ] `doc-required` 
  
  (If you need help on updating docs, create a doc issue)
  
- [ ] `no-need-doc` 
  
  (Please explain why)
  
- [ ] `doc` 
  
  (If this PR contains doc changes)

2022-09-16 14:51 UTC, alpreu requested changes
Thank you for this contribution! I left some comments. Also, I think most of the `log.info` statements should be `log.debug`, right now the log is very noisy.

2022-09-16 14:51 UTC, alpreu commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/checkpoint/CheckpointManager.java
> +            log.error("Failed to update stream checkpoint for key:{},value:{}", key, streamCheckpoint);
Should this not fail the source?

2022-09-16 14:51 UTC, alpreu commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/checkpoint/SessionCheckpoint.java
> +    private String schema;  //bigQuery schema
Why not name the field `bigQuerySchema` instead of leaving a comment? ;)

2022-09-16 14:51 UTC, alpreu commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/BigQuerySourceConfig.java
> +                    + "It is recommended to set this value to null,"
```suggestion
            "BigQuery Authentication key. If not set the source will try to use the GOOGLE_APPLICATION_CREDENTIALS environment variable. 
                    + "It is recommended to set this value to null,"
```

2022-09-16 14:51 UTC, alpreu commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/reader/SourceReader.java
> +    private long curOffset;
```suggestion
    private long currentOffset;
```

2022-09-16 14:51 UTC, alpreu commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/checkpoint/CheckpointManager.java
> +    private StreamCheckpoint curStreamCheckpoint;
```suggestion
    private StreamCheckpoint currentStreamCheckpoint;
```

2022-09-16 14:51 UTC, alpreu commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/reader/SourceReader.java
> +        log.info("all rows had put to queue and wait to complete, stream={} ,endOffset={}", curStream, curOffset);
```suggestion
        log.info("all rows put to queue, waiting to complete, stream={} ,endOffset={}", curStream, curOffset);
```

2022-09-16 14:51 UTC, alpreu commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/reader/SourceReader.java
> +        log.info("stream send to pulsar finish, stream={},ackCount={}", curStream, ackCount);
```suggestion
        log.info("finished sending stream send to pulsar, stream={},ackCount={}", curStream, ackCount);
```

2022-09-16 14:51 UTC, alpreu commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/reader/SourceReader.java
> +        this.processingException = processingException;
I checked this and also the `BigQuerySource`, it looks like `processingException` is never changed to not be 0. Can you confirm if we really use it?

2022-09-16 14:51 UTC, alpreu commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/BigQuerySource.java
> +            throw new IllegalStateException("The connector is already running, exit!");
```suggestion
            log.error("The connector is already running, exiting!");
            throw new IllegalStateException("The connector is already running, exiting!
            ");
```

2022-09-16 14:51 UTC, alpreu commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/BigQuerySource.java
> +                new DefaultThreadFactory("pulsar-bigquery-source-checkpoint"));
Extract the names to constant variables?

2022-09-16 14:51 UTC, alpreu commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/BigQuerySource.java
> +        //节点0进行探测
Is this a leftover comment from development or does it contain relevant info? If the latter, it would be good if it is translated to English

2022-09-16 14:51 UTC, alpreu commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/BigQuerySource.java
> +            log.info("bigquery no data need to be delivery");
```suggestion
            log.info("No data needs to be delivered from BigQuery");
```

2022-09-16 14:51 UTC, alpreu commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/BigQuerySource.java
> +                new DefaultThreadFactory("pulsar-bigquery-source-state-check"));
Same as above, extract names to constant

2022-09-16 14:51 UTC, alpreu commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/BigQuerySource.java
> +            checkpointManager.getSessionCheckpoint(this.sourceContext.getSourceName());
`getSessionCheckpoint(..)` result is ignored?

2022-09-16 14:51 UTC, alpreu commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/BigQuerySource.java
> +            StreamCheckpoint curStreamCheckpoint = checkpointManager.getCurStreamCheckpoint();
```suggestion
            StreamCheckpoint currentStreamCheckpoint = checkpointManager.getCurStreamCheckpoint();
```

2022-09-16 14:51 UTC, alpreu commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/BigQuerySource.java
> +        StreamCheckpoint curStreamCheckpoint = checkpointManager.getCurStreamCheckpoint();
```suggestion
        StreamCheckpoint currentStreamCheckpoint = checkpointManager.getCurStreamCheckpoint();
```

2022-09-16 14:51 UTC, alpreu commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/BigQuerySource.java
> +        AtomicInteger unCompleteStream = new AtomicInteger(sessionCheckpoint.getStreamList().size());
```suggestion
        AtomicInteger incompleteStream = new AtomicInteger(sessionCheckpoint.getStreamList().size());
```

2022-09-16 18:48 UTC, lin-zhao requested changes

2022-09-16 18:48 UTC, lin-zhao commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/BigQuerySource.java
> +        queue = new LinkedBlockingQueue<>(this.getQueueLength());
st
```suggestion
        this.queue = new LinkedBlockingQueue<>(this.getQueueLength());
```

2022-09-16 18:48 UTC, lin-zhao commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/BigQuerySource.java
> +        queue = new LinkedBlockingQueue<>(this.getQueueLength());
Similarly for other class members.

2022-09-16 18:48 UTC, lin-zhao commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/BigQuerySource.java
> +        log.info("total stream size={},streams={},row number={}",
Add more information about this operation. For example, "Discovered stream size={}..."

2022-09-16 18:48 UTC, lin-zhao commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/checkpoint/CheckpointManager.java
> +}
Many files misses the newline at the end of file, as a violation to linux standard. Should be an easy fix to add a new line to each file.

2022-09-16 18:48 UTC, lin-zhao commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/checkpoint/TableViewWrapper.java
> +    private void buildPulsarClient() {
Any particular reason to make this a separate method? It's only used in the constructor and the constructor is only called once.

2022-09-16 18:48 UTC, lin-zhao commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/checkpoint/TableViewWrapper.java
> +        producer.newMessage().value(msgBody).key(key).send();
Again, adding `this.` makes it easier to read.

2022-09-16 18:48 UTC, lin-zhao commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/reader/SourceReader.java
> +    private BinaryDecoder decoder = null;
Isn't `= null` redundant? The other declarations don't explicitly assign to null.

2022-09-16 18:48 UTC, lin-zhao commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/record/BigQueryRecord.java
> +    public BigQueryRecord(org.apache.avro.generic.GenericRecord rowRecordData,
Should add comment to document the parameters.

2022-09-16 18:48 UTC, lin-zhao commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/reader/ReadSessionCreator.java
> +    private TableInfo getActualTable(TableInfo tableInfo) {
Do you need the caller handle `BQConnectorDirectFailException`? If yes how about declaring it in the method?

2022-09-16 18:48 UTC, lin-zhao commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/reader/ReadSessionCreator.java
> +    private String toTablePath(TableId tableId) {
```suggestion
    private String tablePathStr(TableId tableId) {
```

2022-09-26 08:04 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/record/BigQueryRecord.java
> +    }
Because this method is used in unit testing. I will modify it to `protected` and add an annotation of VisibleForTesting.

2022-09-26 08:06 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/package-info.java
> + */
Sure.

2022-09-26 08:16 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/record/BigQueryRecord.java
> +    }
The schema in a session will not change, so as a static var.

2022-09-26 08:24 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/reader/StreamStateChecker.java
> +    private String stream;
`stream` will be used in the log to locate the problem.

2022-09-26 08:26 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/reader/StreamStateChecker.java
> +    private final long maxTimeWait = 1000;
Good suggestion, I will adopt it.

2022-09-26 08:46 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/reader/ReadSessionCreator.java
> +    private String getParent(String project) {
The naming is due to `CreateReadSessionRequest.Builder` uses `setParent` to set the project. 
https://github.com/danpi/pulsar-io-bigquery/blob/bigquery_source_connector_mvp1/src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/reader/ReadSessionCreator.java#L70-L73

2022-09-26 08:48 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/checkpoint/StreamCheckpoint.java
> +    long offset;
Sure, I will change it.

2022-09-26 08:49 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/checkpoint/StreamCheckpoint.java
> +    }
I will remove it.

2022-09-26 09:17 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/checkpoint/StateType.java
> +}
Sure, I will remove `state`

2022-09-26 09:21 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/checkpoint/CheckpointManager.java
> +            throw new BQConnectorDirectFailException("session can not find");
Good suggestion, I'll take it.

2022-09-26 12:42 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/checkpoint/CheckpointManager.java
> +            log.error("Failed to update session checkpoint for key:{},value:{}", key, sessionCheckpoint);
Maybe happen, I have fixed it.

2022-09-26 12:46 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/checkpoint/CheckpointManager.java
> +            log.error("Failed to update stream checkpoint for key:{},value:{}", key, streamCheckpoint);
fix it.

2022-09-26 13:02 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/reader/SourceReader.java
> +        this.processingException = processingException;
Yes, I use `processingException` in the `BigQueryRecord` when the record has failed tobe processed.

2022-09-26 13:05 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/BigQuerySource.java
> +        //节点0进行探测
This is a leftover comment from development, I have removed it.

2022-09-26 13:11 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/BigQuerySource.java
> +            checkpointManager.getSessionCheckpoint(this.sourceContext.getSourceName());
`getSessionCheckpoint` get and set the `checkpointManager.sessionCheckpoint`.

2022-09-26 13:19 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/BigQuerySource.java
> +        AtomicInteger unCompleteStream = new AtomicInteger(sessionCheckpoint.getStreamList().size());
Maybe `uncompleted` is better, what I want to express is unfinished.

2022-09-26 13:22 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/BigQuerySource.java
> +            StreamCheckpoint curStreamCheckpoint = checkpointManager.getCurStreamCheckpoint();
I will change it.

2022-09-26 13:22 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/BigQuerySource.java
> +        StreamCheckpoint curStreamCheckpoint = checkpointManager.getCurStreamCheckpoint();
I will change it.

2022-09-26 13:30 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/BigQuerySource.java
> +                new DefaultThreadFactory("pulsar-bigquery-source-checkpoint"));
done

2022-09-26 13:30 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/BigQuerySource.java
> +                new DefaultThreadFactory("pulsar-bigquery-source-state-check"));
Done.

2022-09-26 13:53 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/checkpoint/CheckpointManager.java
> +}
The new files have added the newline at the end of file, and I have added the configuration to the IDE.

2022-09-26 14:07 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/BigQuerySource.java
> +        queue = new LinkedBlockingQueue<>(this.getQueueLength());
Fix it.

2022-09-26 14:13 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/BigQuerySource.java
> +        log.info("total stream size={},streams={},row number={}",
Done.

2022-09-26 14:23 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/checkpoint/TableViewWrapper.java
> +        producer.newMessage().value(msgBody).key(key).send();
Done

2022-09-26 14:25 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/reader/SourceReader.java
> +    private BinaryDecoder decoder = null;
I will remove it.

2022-09-26 14:46 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/reader/ReadSessionCreator.java
> +    private TableInfo getActualTable(TableInfo tableInfo) {
No, I have changed the method signature.

2022-09-26 14:50 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/reader/ReadSessionCreator.java
> +    private String toTablePath(TableId tableId) {
I have changed it.

2022-09-26 15:05 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/record/BigQueryRecord.java
> +    public BigQueryRecord(org.apache.avro.generic.GenericRecord rowRecordData,
Done.

2022-09-26 16:37 UTC, lin-zhao approved these changes

2022-09-27 08:12 UTC, danpi commented on src/test/java/org/apache/pulsar/ecosystem/io/bigquery/source/record/BigQueryRecordTest.java
> +            + "}\n";
After JDK13, `Text Blocks` are supported, but now we use `JDK1.8`.

2022-09-27 08:44 UTC, danpi commented on src/main/java/org/apache/pulsar/ecosystem/io/bigquery/source/reader/StreamStateChecker.java
> +            }
In this case, I want to wait until all the messages have been ACK, and then the source will get the next stream.

2022-10-09 09:34 UTC, closed without merging